name: men
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  camera: ^0.5.8+2
  tflite: 1.0.4
  flutter_local_notifications: ^1.4.4+1
  android_alarm_manager: ^0.4.5+11
  device_info: ^0.4.2+4
  data_connection_checker: ^0.3.4
  connectivity: ^0.4.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/